site_name: Embroidermodder Reference Manual
site_description: The design, analysis and rationale of all Embroidermodder projects
copyright: Copyright (C) 2013-2024 The Embroidermodder Team
site_url: https://www.libembroidery.org/docs
repo_url: https://github.com/Embroidermodder/refman/
nav:
  - Home: index.md
  - About: about.md
  - To Do: todo.md
theme:
  name: material
plugins:
  - search
  - bibtex:
      bib_file: "references.bib"
markdown_extensions:
  - footnotes
