name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Deps
        run: bash scripts/deps.sh
      - name: Build
        run: bash scripts/build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: refman
          path: ./emrm.pdf
